### ISSUE TITLE
Service not Start

### ISSUE THREAD

**Issue by Jeffreyveggie** [ariscop/postgresql-readynas#1]
The Postgres service 1 sekunde Down ..

perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
psql: could not connect to server: Connection refused
        Is the server running on host "xxx.xxx.xxx.xxx" and accepting
        TCP/IP connections on port 4001?
root@nas-3
root@nas-3

 PID USER      PR  NI  VIRT  RES  SHR S  %CPU %MEM    TIME+  COMMAND
 3965 postgres  20   0 15500 2976 2256 R  55.3  0.6   0:01.68 postgres

**Comment by ariscop** [comment]
Can you paste the output of systemctl status fvapp-postgresql-readynas

**Comment by Jeffreyveggie** [comment]
root@nas-34-2A-E4:~# systemctl status fvapp-postgresql-readynas
fvapp-postgresql-readynas.service - Service for postgresql
          Loaded: loaded (/lib/systemd/system/fvapp-postgresql-readynas.service; disabled)
          Active: failed (Result: exit-code) since Wed, 04 Mar 2015 13:48:18 -0800; 8h ago
         Process: 13380 ExecStop=/usr/lib/postgresql/9.1/bin/pg_ctl -D /apps/postgresql-readynas/db stop (code=exited, status=1/FAILURE)
         Process: 13365 ExecStart=/usr/lib/postgresql/9.1/bin/postgres -D /apps/postgresql-readynas/db (code=exited, status=1/FAILURE)
          CGroup: name=systemd:/system/fvapp-postgresql-readynas.service

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.

**Comment by ariscop** [comment]
systemctl restart fvapp-postgresql-readynas
systemctl status fvapp-postgresql-readynas

i need to see what it logs on startup

**Comment by Jeffreyveggie** [comment]
Sorry , This Commands is Error NO Output

**Comment by Jeffreyveggie** [comment]
root@nas-34-2A-E4:~# systemctl restart fvapp-postgresql-readynas
root@nas-34-2A-E4:~# systemctl status fvapp-postgresql-readynas
fvapp-postgresql-readynas.service - Service for postgresql
          Loaded: loaded (/lib/systemd/system/fvapp-postgresql-readynas.service; disabled)
          Active: active (running) since Wed, 04 Mar 2015 22:18:26 -0800; 5s ago
         Process: 13380 ExecStop=/usr/lib/postgresql/9.1/bin/pg_ctl -D /apps/postgresql-readynas/db stop (code=exited, status=1/FAILURE)
        Main PID: 21912 (postgres)
          CGroup: name=systemd:/system/fvapp-postgresql-readynas.service
                  └ 21912 /usr/lib/postgresql/9.1/bin/postgres -D /apps/post...

**Comment by ariscop** [comment]
So it is running now, but was not running after you installed it?
I think it is doing something similar on my nas after rebooting, will have a look.

Restarting it will fix the probem
either by turning it off and on in the settings or using systemctl restart fvapp-postgresql-readynas

**Comment by Jeffreyveggie** [comment]
Will it even try ; )

The app simply does not run

**Comment by Jeffreyveggie** [comment]
<spoiler>Nas 104 Dumb

Unit postgresql.service:
    Description: LSB: PostgreSQL RDBMS server
    Instance: n/a
    Unit Load State: loaded
    Unit Active State: inactive
    Inactive Exit Timestamp: n/a
    Active Enter Timestamp: n/a
    Active Exit Timestamp: n/a
    Inactive Enter Timestamp: n/a
    GC Check Good: yes
    Need Daemon Reload: no
    Name: postgresql.service
    Requires: systemd-journald.socket
    Requires: basic.target
    Conflicts: shutdown.target
    Before: shutdown.target
    After: local-fs.target
    After: remote-fs.target
    After: network.target
    After: time-sync.target
    After: syslog.target
    After: systemd-journald.socket
    After: basic.target
    References: local-fs.target
    References: remote-fs.target
    References: network.target
    References: time-sync.target
    References: syslog.target
    References: systemd-journald.socket
    References: basic.target
    References: shutdown.target
    StopWhenUnneeded: no
    RefuseManualStart: no
    RefuseManualStop: no
    DefaultDependencies: yes
    OnFailureIsolate: no
    IgnoreOnIsolate: no
    IgnoreOnSnapshot: no
    ControlGroup: cpu:/system/postgresql.service
    ControlGroup: name=systemd:/system/postgresql.service
    Service State: dead
    Result: success
    Reload Result: success
    PermissionsStartOnly: no
    RootDirectoryStartOnly: no
    RemainAfterExit: yes
    GuessMainPID: no
    Type: forking
    Restart: no
    NotifyAccess: none
    UMask: 0022
    WorkingDirectory: /
    RootDirectory: /
    NonBlocking: no
    PrivateTmp: no
    ControlGroupModify: no
    ControlGroupPersistent: yes
    PrivateNetwork: no
    LimitNOFILE: 4096
    StandardInput: null
    StandardOutput: journal+console
    StandardError: inherit
    SyslogFacility: daemon
    SyslogLevel: info
    KillMode: process
    KillSignal: SIGTERM
    SendSIGKILL: yes
    IgnoreSIGPIPE: no
    -> ExecStart:
        Command Line: /etc/init.d/postgresql start
    -> ExecReload:
        Command Line: /etc/init.d/postgresql reload
    -> ExecStop:
        Command Line: /etc/init.d/postgresql stop
    SysV Init Script Path: /etc/init.d/postgresql
    SysV Init Script has LSB Header: yes
    SysVEnabled: no
    SysVRunLevels: 2345
<spoiler>Nas 104 Dumb

**Comment by Jeffreyveggie** [comment]
More Sorry ;) I am will Help You 

---

/etc/sysctl.d:
total 12
-rw-r--r-- 1  115 guest  27 Jan 11  2014 00-min-free-kbytes.conf
-rw-r--r-- 1 root root  337 Sep  2  2013 30-postgresql-shm.conf
-rw-r--r-- 1 root root  639 May 19  2012 README.sysctl

lrwxrwxrwx 1 root root 35 Mar  4 04:33 apache2.service -> /lib/systemd/system/apache2.service
lrwxrwxrwx 1 root root 30 Mar  4 04:33 apps.mount -> /lib/systemd/system/apps.mount
lrwxrwxrwx 1 root root 36 Mar  4 04:33 apt-update.timer -> /lib/systemd/system/apt-update.timer
lrwxrwxrwx 1 root root 40 Mar  4 04:33 avahi-daemon.service -> /lib/systemd/system/avahi-daemon.service
lrwxrwxrwx 1 root root 35 Mar  4 04:33 connman.service -> /lib/systemd/system/connman.service
lrwxrwxrwx 1 root root 32 Mar  4 04:33 cron.service -> /lib/systemd/system/cron.service
lrwxrwxrwx 1 root root 53 Mar  4 23:32 fvapp-postgresql-readynas.service -> /lib/systemd/system/fvapp-postgresql-readynas.service
lrwxrwxrwx 1 root root 38 Mar  4 04:33 fvbackup-q.service -> /lib/systemd/system/fvbackup-q.service
lrwxrwxrwx 1 root root 30 Mar  4 04:33 home.mount -> /lib/systemd/system/home.mount
lrwxrwxrwx 1 root root 33 Mar  4 04:33 hwclock.timer -> /lib/systemd/system/hwclock.timer
lrwxrwxrwx 1 root root 37 Mar  4 04:33 logtruncate.timer -> /lib/systemd/system/logtruncate.timer
lrwxrwxrwx 1 root root 33 Mar  4 04:33 mdadm.service -> /lib/systemd/system/mdadm.service
lrwxrwxrwx 1 root root 36 Mar  4 04:34 minidlna.service -> /lib/systemd/system/minidlna.service

/etc/rc6.d:
total 4
lrwxrwxrwx 1 root root  16 Mar  4 04:33 K01lsyncd -> ../init.d/lsyncd
lrwxrwxrwx 1 root root  20 Mar  4 04:33 K01nut-server -> ../init.d/nut-server
lrwxrwxrwx 1 root root  20 Mar  4 04:38 K01postgresql -> ../init.d/postgresql
-rw-r--r-- 1 root root 351 Oct 15  2012 README

lrwxrwxrwx 1 root root  20 Mar  4 04:38 K01postgresql -> ../init.d/postgresql
-rw-r--r-- 1 root root 677 Jul 14  2013 README

**Comment by Jeffreyveggie** [comment]
Start-Date: 2015-03-04  04:35:33
Commandline: apt-get install -f freeapp-collection
Install: freeapp-collection:armel (1423618855)
End-Date: 2015-03-04  04:35:39

Start-Date: 2015-03-04  06:25:44
Commandline: apt-get -y purge postgresql-readynas
Purge: postgresql-readynas:armel (9.1)
End-Date: 2015-03-04  06:25:48

**Comment by ariscop** [comment]
Seems it has problems creating the pid file

**Comment by Jeffreyveggie** [comment]
I have no idea , I have to tuhen only ignorant of things of which I have no idea

**Comment by ariscop** [comment]
https://github.com/ariscop/postgresql-readynas/releases/tag/9.1%2B1

Should fix the problem

**Comment by ariscop** [comment]
I've submitted the fixed version but it could take any ammount of time to get through the netgear guys

**Comment by Jeffreyveggie** [comment]
Negative...

**Comment by Jeffreyveggie** [comment]
At first it did not run with the command

/etc/init.d/postgresql start , in ssh, it works even after reboot because everything seems in order, will now create data bank and test ..

Thank you for the Work etc
