### ISSUE TITLE
Password

### ISSUE THREAD

**Issue by DonBaronFactory** [ariscop/postgresql-readynas#2]
What is the default password set for the postgres user? Or with which user can I connect the DB Server on the ReadyNas?

**Comment by ariscop** [comment]
The admin account you use to log in to the web interface should work for postgres, The [postinst script](https://github.com/ariscop/postgresql-readynas/blob/master/debian/postinst#L35-L38) sets that up

**Comment by ariscop** [comment]
This package is also very likely to break soon, readynas is moving to a newer version of debian and i no longer have the nas this was for

**Comment by DonBaronFactory** [comment]
thanks ... got it to work, had to create a unix user first and then the same on psql...
